/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/animations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description API endpoint for creating and managing multi-frame animation jobs.
         *
         *     A POST request to this endpoint will create a parent `Animation` object
         *     and automatically spawn a child `Job` for each frame in the sequence,
         *     or a grid of `Job`s for tiled animations.
         */
        get: operations["api_animations_list"];
        put?: never;
        /**
         * @description API endpoint for creating and managing multi-frame animation jobs.
         *
         *     A POST request to this endpoint will create a parent `Animation` object
         *     and automatically spawn a child `Job` for each frame in the sequence,
         *     or a grid of `Job`s for tiled animations.
         */
        post: operations["api_animations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description API endpoint for creating and managing multi-frame animation jobs.
         *
         *     A POST request to this endpoint will create a parent `Animation` object
         *     and automatically spawn a child `Job` for each frame in the sequence,
         *     or a grid of `Job`s for tiled animations.
         */
        get: operations["api_animations_retrieve"];
        /**
         * @description API endpoint for creating and managing multi-frame animation jobs.
         *
         *     A POST request to this endpoint will create a parent `Animation` object
         *     and automatically spawn a child `Job` for each frame in the sequence,
         *     or a grid of `Job`s for tiled animations.
         */
        put: operations["api_animations_update"];
        post?: never;
        /**
         * @description API endpoint for creating and managing multi-frame animation jobs.
         *
         *     A POST request to this endpoint will create a parent `Animation` object
         *     and automatically spawn a child `Job` for each frame in the sequence,
         *     or a grid of `Job`s for tiled animations.
         */
        delete: operations["api_animations_destroy"];
        options?: never;
        head?: never;
        /**
         * @description API endpoint for creating and managing multi-frame animation jobs.
         *
         *     A POST request to this endpoint will create a parent `Animation` object
         *     and automatically spawn a child `Job` for each frame in the sequence,
         *     or a grid of `Job`s for tiled animations.
         */
        patch: operations["api_animations_partial_update"];
        trace?: never;
    };
    "/api/assets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description API endpoint for uploading and managing .blend file assets.
         *     Assets are uploaded as multipart/form-data.
         */
        get: operations["api_assets_list"];
        put?: never;
        /**
         * @description API endpoint for uploading and managing .blend file assets.
         *     Assets are uploaded as multipart/form-data.
         */
        post: operations["api_assets_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description API endpoint for uploading and managing .blend file assets.
         *     Assets are uploaded as multipart/form-data.
         */
        get: operations["api_assets_retrieve"];
        /**
         * @description API endpoint for uploading and managing .blend file assets.
         *     Assets are uploaded as multipart/form-data.
         */
        put: operations["api_assets_update"];
        post?: never;
        /**
         * @description API endpoint for uploading and managing .blend file assets.
         *     Assets are uploaded as multipart/form-data.
         */
        delete: operations["api_assets_destroy"];
        options?: never;
        head?: never;
        /**
         * @description API endpoint for uploading and managing .blend file assets.
         *     Assets are uploaded as multipart/form-data.
         */
        patch: operations["api_assets_partial_update"];
        trace?: never;
    };
    "/api/heartbeat/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists all registered workers. */
        get: operations["api_heartbeat_retrieve"];
        put?: never;
        /**
         * @description Handles worker registration and periodic heartbeats.
         *
         *     Args:
         *         request: The request object containing worker data.
         *
         *     Returns:
         *         A Response containing the worker's data.
         */
        post: operations["api_heartbeat_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description API endpoint that allows render jobs to be viewed or created.
         *
         *     Workers use this endpoint to poll for new jobs, claim them for rendering,
         *     and update their status and final output.
         */
        get: operations["api_jobs_list"];
        put?: never;
        /**
         * @description API endpoint that allows render jobs to be viewed or created.
         *
         *     Workers use this endpoint to poll for new jobs, claim them for rendering,
         *     and update their status and final output.
         */
        post: operations["api_jobs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description API endpoint that allows render jobs to be viewed or created.
         *
         *     Workers use this endpoint to poll for new jobs, claim them for rendering,
         *     and update their status and final output.
         */
        get: operations["api_jobs_retrieve"];
        /**
         * @description API endpoint that allows render jobs to be viewed or created.
         *
         *     Workers use this endpoint to poll for new jobs, claim them for rendering,
         *     and update their status and final output.
         */
        put: operations["api_jobs_update"];
        post?: never;
        /**
         * @description API endpoint that allows render jobs to be viewed or created.
         *
         *     Workers use this endpoint to poll for new jobs, claim them for rendering,
         *     and update their status and final output.
         */
        delete: operations["api_jobs_destroy"];
        options?: never;
        head?: never;
        /**
         * @description API endpoint that allows render jobs to be viewed or created.
         *
         *     Workers use this endpoint to poll for new jobs, claim them for rendering,
         *     and update their status and final output.
         */
        patch: operations["api_jobs_partial_update"];
        trace?: never;
    };
    "/api/jobs/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Cancels a render job, setting its status to 'CANCELED'.
         *
         *     Args:
         *         request: The request object.
         *         pk: The primary key of the job to cancel.
         *
         *     Returns:
         *         A Response containing the updated job data.
         */
        post: operations["api_jobs_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/claim/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Atomically claim a job for a worker.
         *
         *     Uses SELECT FOR UPDATE to lock the job row, preventing race
         *     conditions where multiple workers claim the same job.
         *
         *     Expects a JSON body with `worker_id` (the Worker primary key).
         *
         *     Returns:
         *         200 on success with updated job data.
         *         400 if worker_id is missing or invalid.
         *         404 if job not found.
         *         409 if job is already claimed or not in QUEUED status.
         */
        post: operations["api_jobs_claim_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/upload_output/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Action for a worker to upload the final rendered output file for a job.
         *
         *     Expects a multipart/form-data request with a file field named `output_file`.
         *     Validates the file is a valid image within the configured size limit.
         *     Saving the file will trigger a signal to generate the thumbnail.
         */
        post: operations["api_jobs_upload_output_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description API endpoint for creating, retrieving, and managing rendering projects.
         *
         *     Projects serve as the top-level organizational entity for assets and jobs.
         *     They can be paused to temporarily stop workers from processing their jobs.
         */
        get: operations["api_projects_list"];
        put?: never;
        /**
         * @description API endpoint for creating, retrieving, and managing rendering projects.
         *
         *     Projects serve as the top-level organizational entity for assets and jobs.
         *     They can be paused to temporarily stop workers from processing their jobs.
         */
        post: operations["api_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description API endpoint for creating, retrieving, and managing rendering projects.
         *
         *     Projects serve as the top-level organizational entity for assets and jobs.
         *     They can be paused to temporarily stop workers from processing their jobs.
         */
        get: operations["api_projects_retrieve"];
        /**
         * @description API endpoint for creating, retrieving, and managing rendering projects.
         *
         *     Projects serve as the top-level organizational entity for assets and jobs.
         *     They can be paused to temporarily stop workers from processing their jobs.
         */
        put: operations["api_projects_update"];
        post?: never;
        /**
         * @description API endpoint for creating, retrieving, and managing rendering projects.
         *
         *     Projects serve as the top-level organizational entity for assets and jobs.
         *     They can be paused to temporarily stop workers from processing their jobs.
         */
        delete: operations["api_projects_destroy"];
        options?: never;
        head?: never;
        /**
         * @description API endpoint for creating, retrieving, and managing rendering projects.
         *
         *     Projects serve as the top-level organizational entity for assets and jobs.
         *     They can be paused to temporarily stop workers from processing their jobs.
         */
        patch: operations["api_projects_partial_update"];
        trace?: never;
    };
    "/api/projects/{id}/pause/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Pauses a project, preventing workers from picking up any of its jobs.
         *
         *     Args:
         *         request: The request object.
         *         pk: The primary key of the project to pause.
         *
         *     Returns:
         *         A Response containing the updated project data.
         */
        post: operations["api_projects_pause_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/unpause/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Unpauses a project, allowing workers to resume processing its jobs.
         *
         *     Args:
         *         request: The request object.
         *         pk: The primary key of the project to unpause.
         *
         *     Returns:
         *         A Response containing the updated project data.
         */
        post: operations["api_projects_unpause_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Returns aggregate statistics for the manager dashboard.
         *
         *     All counts use database-level aggregation to avoid N+1 queries.
         */
        get: operations["api_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiled-jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description API endpoint for creating and managing Tiled Render jobs.
         *
         *     A POST request to this endpoint will create a parent `TiledJob` object and
         *     automatically spawn a child `Job` for each tile in the specified grid.
         *     These tile jobs contain the necessary render border overrides.
         */
        get: operations["api_tiled_jobs_list"];
        put?: never;
        /**
         * @description API endpoint for creating and managing Tiled Render jobs.
         *
         *     A POST request to this endpoint will create a parent `TiledJob` object and
         *     automatically spawn a child `Job` for each tile in the specified grid.
         *     These tile jobs contain the necessary render border overrides.
         */
        post: operations["api_tiled_jobs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiled-jobs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description API endpoint for creating and managing Tiled Render jobs.
         *
         *     A POST request to this endpoint will create a parent `TiledJob` object and
         *     automatically spawn a child `Job` for each tile in the specified grid.
         *     These tile jobs contain the necessary render border overrides.
         */
        get: operations["api_tiled_jobs_retrieve"];
        /**
         * @description API endpoint for creating and managing Tiled Render jobs.
         *
         *     A POST request to this endpoint will create a parent `TiledJob` object and
         *     automatically spawn a child `Job` for each tile in the specified grid.
         *     These tile jobs contain the necessary render border overrides.
         */
        put: operations["api_tiled_jobs_update"];
        post?: never;
        /**
         * @description API endpoint for creating and managing Tiled Render jobs.
         *
         *     A POST request to this endpoint will create a parent `TiledJob` object and
         *     automatically spawn a child `Job` for each tile in the specified grid.
         *     These tile jobs contain the necessary render border overrides.
         */
        delete: operations["api_tiled_jobs_destroy"];
        options?: never;
        head?: never;
        /**
         * @description API endpoint for creating and managing Tiled Render jobs.
         *
         *     A POST request to this endpoint will create a parent `TiledJob` object and
         *     automatically spawn a child `Job` for each tile in the specified grid.
         *     These tile jobs contain the necessary render border overrides.
         */
        patch: operations["api_tiled_jobs_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Serializer for the `Animation` model.
         *
         *     This serializer includes custom fields to report progress and links to the
         *     child `AnimationFrame` objects for tiled animations.
         */
        Animation: {
            readonly id: number;
            name: string;
            readonly status: components["schemas"]["Status1b9Enum"];
            /** @description Human-readable progress string (e.g., '3 of 10 frames complete'). */
            readonly progress: string;
            /** @description The total number of frames in the animation. */
            readonly total_frames: string;
            /** @description The number of frames that are in a 'DONE' status. */
            readonly completed_frames: string;
            /** Format: uuid */
            project: string;
            readonly project_details: components["schemas"]["Project"];
            readonly asset: components["schemas"]["Asset"];
            asset_id: number;
            output_file_pattern: string;
            /** Format: int64 */
            start_frame: number;
            /** Format: int64 */
            end_frame: number;
            /**
             * Format: int64
             * @description Number of frames to advance animation between renders (e.g., a step of 2 renders every other frame).
             */
            frame_step?: number;
            /** @description e.g., '4.5' or '4.1.1' */
            blender_version?: string;
            render_engine?: components["schemas"]["RenderEngineEnum"];
            render_device?: components["schemas"]["RenderDeviceEnum"];
            cycles_feature_set?: components["schemas"]["CyclesFeatureSetEnum"];
            /** @description Blender render settings overrides, e.g., {'cycles.samples': 128, 'resolution_x': 1920} */
            render_settings?: unknown;
            /**
             * @description Grid size for tiled rendering of each frame.
             *
             *     * `NONE` - None
             *     * `2x2` - 2x2 (4 Tiles)
             *     * `3x3` - 3x3 (9 Tiles)
             *     * `4x4` - 4x4 (16 Tiles)
             *     * `5x5` - 5x5 (25 Tiles)
             */
            tiling_config?: components["schemas"]["TilingConfigEnum"];
            /** Format: date-time */
            readonly submitted_at: string;
            /** Format: date-time */
            readonly completed_at: string | null;
            /** @description The cumulative render time of all completed frames in this animation. */
            readonly total_render_time_seconds: number;
            /**
             * Format: uri
             * @description A preview thumbnail of the latest completed frame.
             */
            readonly thumbnail: string | null;
            /** @description List of child frames for tiled animations. */
            readonly frames: components["schemas"]["AnimationFrame"][];
        };
        /** @description Serializer for the individual, assembled frames of a tiled animation. */
        AnimationFrame: {
            readonly id: number;
            /** Format: int64 */
            frame_number: number;
            status?: components["schemas"]["AnimationFrameStatusEnum"];
            /**
             * Format: uri
             * @description The final, assembled output image for this frame.
             */
            output_file?: string | null;
            /**
             * Format: uri
             * @description A preview thumbnail of this assembled frame.
             */
            thumbnail?: string | null;
            /** Format: int64 */
            render_time_seconds?: number;
        };
        /**
         * @description * `PENDING` - Pending
         *     * `RENDERING` - Rendering
         *     * `ASSEMBLING` - Assembling
         *     * `DONE` - Done
         *     * `ERROR` - Error
         * @enum {string}
         */
        AnimationFrameStatusEnum: "PENDING" | "RENDERING" | "ASSEMBLING" | "DONE" | "ERROR";
        /** @description Serializer for the `Asset` model, handling file uploads. */
        Asset: {
            readonly id: number;
            /** @description A unique name for the asset file. */
            name: string;
            /**
             * Format: uri
             * @description The uploaded .blend file.
             */
            blend_file: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            project: string;
            readonly project_details: components["schemas"]["Project"];
        };
        /**
         * @description * `SUPPORTED` - Supported
         *     * `EXPERIMENTAL` - Experimental
         * @enum {string}
         */
        CyclesFeatureSetEnum: "SUPPORTED" | "EXPERIMENTAL";
        DashboardStats: {
            workers: {
                [key: string]: unknown;
            };
            jobs: {
                [key: string]: unknown;
            };
            projects: {
                [key: string]: unknown;
            };
            recent_completions: unknown[];
        };
        /**
         * @description Serializer for the `Job` model.
         *
         *     This serializer is used by the API for creating, viewing, and updating jobs.
         *     It includes read-only fields for human-readable status and worker hostname.
         *     Fields updated by the worker agent during its lifecycle (e.g., `assigned_worker`,
         *     `started_at`, `completed_at`, `last_output`, `error_message`) are now
         *     writable to allow status updates via PATCH requests.
         */
        Job: {
            readonly id: number;
            /** @description A unique name for the render job within its asset. */
            name: string;
            readonly asset: components["schemas"]["Asset"];
            asset_id: number;
            /** @description Output file path pattern (e.g., //render/#.png) */
            output_file_pattern: string;
            /** Format: int64 */
            start_frame?: number;
            /** Format: int64 */
            end_frame?: number;
            status?: components["schemas"]["Status1b9Enum"];
            /** @description The human-readable status of the job. */
            readonly status_display: string;
            readonly assigned_worker: number | null;
            /** @description The hostname of the worker assigned to this job. */
            readonly assigned_worker_hostname: string;
            animation?: number | null;
            /** Format: uuid */
            readonly tiled_job: string | null;
            readonly animation_frame: number | null;
            /** Format: date-time */
            readonly submitted_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** @description e.g., '4.5' or '4.1.1' */
            blender_version?: string;
            render_engine?: components["schemas"]["RenderEngineEnum"];
            render_device?: components["schemas"]["RenderDeviceEnum"];
            cycles_feature_set?: components["schemas"]["CyclesFeatureSetEnum"];
            /** @description Blender render settings overrides, e.g., {'cycles.samples': 128, 'resolution_x': 1920} */
            render_settings?: unknown;
            last_output?: string;
            error_message?: string;
            /**
             * Format: int64
             * @description The total time in seconds this job took to render.
             */
            render_time_seconds?: number | null;
            /**
             * Format: uri
             * @description The final rendered output file uploaded by the worker.
             */
            readonly output_file: string | null;
            /**
             * Format: uri
             * @description A preview thumbnail of the final render.
             */
            readonly thumbnail: string | null;
        };
        /**
         * @description Serializer for the `Animation` model.
         *
         *     This serializer includes custom fields to report progress and links to the
         *     child `AnimationFrame` objects for tiled animations.
         */
        PatchedAnimation: {
            readonly id?: number;
            name?: string;
            readonly status?: components["schemas"]["Status1b9Enum"];
            /** @description Human-readable progress string (e.g., '3 of 10 frames complete'). */
            readonly progress?: string;
            /** @description The total number of frames in the animation. */
            readonly total_frames?: string;
            /** @description The number of frames that are in a 'DONE' status. */
            readonly completed_frames?: string;
            /** Format: uuid */
            project?: string;
            readonly project_details?: components["schemas"]["Project"];
            readonly asset?: components["schemas"]["Asset"];
            asset_id?: number;
            output_file_pattern?: string;
            /** Format: int64 */
            start_frame?: number;
            /** Format: int64 */
            end_frame?: number;
            /**
             * Format: int64
             * @description Number of frames to advance animation between renders (e.g., a step of 2 renders every other frame).
             */
            frame_step?: number;
            /** @description e.g., '4.5' or '4.1.1' */
            blender_version?: string;
            render_engine?: components["schemas"]["RenderEngineEnum"];
            render_device?: components["schemas"]["RenderDeviceEnum"];
            cycles_feature_set?: components["schemas"]["CyclesFeatureSetEnum"];
            /** @description Blender render settings overrides, e.g., {'cycles.samples': 128, 'resolution_x': 1920} */
            render_settings?: unknown;
            /**
             * @description Grid size for tiled rendering of each frame.
             *
             *     * `NONE` - None
             *     * `2x2` - 2x2 (4 Tiles)
             *     * `3x3` - 3x3 (9 Tiles)
             *     * `4x4` - 4x4 (16 Tiles)
             *     * `5x5` - 5x5 (25 Tiles)
             */
            tiling_config?: components["schemas"]["TilingConfigEnum"];
            /** Format: date-time */
            readonly submitted_at?: string;
            /** Format: date-time */
            readonly completed_at?: string | null;
            /** @description The cumulative render time of all completed frames in this animation. */
            readonly total_render_time_seconds?: number;
            /**
             * Format: uri
             * @description A preview thumbnail of the latest completed frame.
             */
            readonly thumbnail?: string | null;
            /** @description List of child frames for tiled animations. */
            readonly frames?: components["schemas"]["AnimationFrame"][];
        };
        /** @description Serializer for the `Asset` model, handling file uploads. */
        PatchedAsset: {
            readonly id?: number;
            /** @description A unique name for the asset file. */
            name?: string;
            /**
             * Format: uri
             * @description The uploaded .blend file.
             */
            blend_file?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: uuid */
            project?: string;
            readonly project_details?: components["schemas"]["Project"];
        };
        /**
         * @description Serializer for the `Job` model.
         *
         *     This serializer is used by the API for creating, viewing, and updating jobs.
         *     It includes read-only fields for human-readable status and worker hostname.
         *     Fields updated by the worker agent during its lifecycle (e.g., `assigned_worker`,
         *     `started_at`, `completed_at`, `last_output`, `error_message`) are now
         *     writable to allow status updates via PATCH requests.
         */
        PatchedJob: {
            readonly id?: number;
            /** @description A unique name for the render job within its asset. */
            name?: string;
            readonly asset?: components["schemas"]["Asset"];
            asset_id?: number;
            /** @description Output file path pattern (e.g., //render/#.png) */
            output_file_pattern?: string;
            /** Format: int64 */
            start_frame?: number;
            /** Format: int64 */
            end_frame?: number;
            status?: components["schemas"]["Status1b9Enum"];
            /** @description The human-readable status of the job. */
            readonly status_display?: string;
            readonly assigned_worker?: number | null;
            /** @description The hostname of the worker assigned to this job. */
            readonly assigned_worker_hostname?: string;
            animation?: number | null;
            /** Format: uuid */
            readonly tiled_job?: string | null;
            readonly animation_frame?: number | null;
            /** Format: date-time */
            readonly submitted_at?: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** @description e.g., '4.5' or '4.1.1' */
            blender_version?: string;
            render_engine?: components["schemas"]["RenderEngineEnum"];
            render_device?: components["schemas"]["RenderDeviceEnum"];
            cycles_feature_set?: components["schemas"]["CyclesFeatureSetEnum"];
            /** @description Blender render settings overrides, e.g., {'cycles.samples': 128, 'resolution_x': 1920} */
            render_settings?: unknown;
            last_output?: string;
            error_message?: string;
            /**
             * Format: int64
             * @description The total time in seconds this job took to render.
             */
            render_time_seconds?: number | null;
            /**
             * Format: uri
             * @description The final rendered output file uploaded by the worker.
             */
            readonly output_file?: string | null;
            /**
             * Format: uri
             * @description A preview thumbnail of the final render.
             */
            readonly thumbnail?: string | null;
        };
        /** @description Serializer for the `Project` model. */
        PatchedProject: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** @description If true, workers will not pick up jobs from this project. */
            readonly is_paused?: boolean;
        };
        /**
         * @description Serializer for the `TiledJob` model.
         *
         *     Includes calculated fields for progress and tile counts.
         */
        PatchedTiledJob: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            readonly status?: components["schemas"]["TiledJobStatusEnum"];
            /** @description Human-readable progress string (e.g., '3 of 10 tiles complete'). */
            readonly progress?: string;
            /** @description The total number of tiles in the job. */
            readonly total_tiles?: string;
            /** @description The number of tiles that are in a 'DONE' status. */
            readonly completed_tiles?: string;
            /** Format: uuid */
            project?: string;
            readonly project_details?: components["schemas"]["Project"];
            readonly asset?: components["schemas"]["Asset"];
            asset_id?: number;
            /** Format: int64 */
            final_resolution_x?: number;
            /** Format: int64 */
            final_resolution_y?: number;
            /** Format: int64 */
            tile_count_x?: number;
            /** Format: int64 */
            tile_count_y?: number;
            blender_version?: string;
            render_engine?: components["schemas"]["RenderEngineEnum"];
            render_device?: components["schemas"]["RenderDeviceEnum"];
            cycles_feature_set?: components["schemas"]["CyclesFeatureSetEnum"];
            /** @description Global render settings for all tiles. */
            render_settings?: unknown;
            /** Format: date-time */
            readonly submitted_at?: string;
            /** Format: date-time */
            readonly completed_at?: string | null;
            readonly total_render_time_seconds?: number;
            /**
             * Format: uri
             * @description The final, assembled output image.
             */
            readonly output_file?: string | null;
            /**
             * Format: uri
             * @description A preview thumbnail of the final assembled image.
             */
            readonly thumbnail?: string | null;
        };
        /** @description Serializer for the `Project` model. */
        Project: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: date-time */
            readonly created_at: string;
            /** @description If true, workers will not pick up jobs from this project. */
            readonly is_paused: boolean;
        };
        /**
         * @description * `CPU` - CPU Only
         *     * `GPU` - GPU Only
         *     * `ANY` - Any Available Device
         * @enum {string}
         */
        RenderDeviceEnum: "CPU" | "GPU" | "ANY";
        /**
         * @description * `CYCLES` - Cycles
         *     * `BLENDER_EEVEE_NEXT` - Eevee
         *     * `WORKBENCH` - Workbench
         * @enum {string}
         */
        RenderEngineEnum: "CYCLES" | "BLENDER_EEVEE_NEXT" | "WORKBENCH";
        /**
         * @description * `QUEUED` - Queued
         *     * `RENDERING` - Rendering
         *     * `DONE` - Done
         *     * `ERROR` - Error
         *     * `CANCELED` - Canceled
         * @enum {string}
         */
        Status1b9Enum: "QUEUED" | "RENDERING" | "DONE" | "ERROR" | "CANCELED";
        /**
         * @description Serializer for the `TiledJob` model.
         *
         *     Includes calculated fields for progress and tile counts.
         */
        TiledJob: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            readonly status: components["schemas"]["TiledJobStatusEnum"];
            /** @description Human-readable progress string (e.g., '3 of 10 tiles complete'). */
            readonly progress: string;
            /** @description The total number of tiles in the job. */
            readonly total_tiles: string;
            /** @description The number of tiles that are in a 'DONE' status. */
            readonly completed_tiles: string;
            /** Format: uuid */
            project: string;
            readonly project_details: components["schemas"]["Project"];
            readonly asset: components["schemas"]["Asset"];
            asset_id: number;
            /** Format: int64 */
            final_resolution_x: number;
            /** Format: int64 */
            final_resolution_y: number;
            /** Format: int64 */
            tile_count_x?: number;
            /** Format: int64 */
            tile_count_y?: number;
            blender_version?: string;
            render_engine?: components["schemas"]["RenderEngineEnum"];
            render_device?: components["schemas"]["RenderDeviceEnum"];
            cycles_feature_set?: components["schemas"]["CyclesFeatureSetEnum"];
            /** @description Global render settings for all tiles. */
            render_settings?: unknown;
            /** Format: date-time */
            readonly submitted_at: string;
            /** Format: date-time */
            readonly completed_at: string | null;
            readonly total_render_time_seconds: number;
            /**
             * Format: uri
             * @description The final, assembled output image.
             */
            readonly output_file: string | null;
            /**
             * Format: uri
             * @description A preview thumbnail of the final assembled image.
             */
            readonly thumbnail: string | null;
        };
        /**
         * @description * `QUEUED` - Queued
         *     * `RENDERING` - Rendering
         *     * `ASSEMBLING` - Assembling
         *     * `DONE` - Done
         *     * `ERROR` - Error
         * @enum {string}
         */
        TiledJobStatusEnum: "QUEUED" | "RENDERING" | "ASSEMBLING" | "DONE" | "ERROR";
        /**
         * @description * `NONE` - None
         *     * `2x2` - 2x2 (4 Tiles)
         *     * `3x3` - 3x3 (9 Tiles)
         *     * `4x4` - 4x4 (16 Tiles)
         *     * `5x5` - 5x5 (25 Tiles)
         * @enum {string}
         */
        TilingConfigEnum: "NONE" | "2x2" | "3x3" | "4x4" | "5x5";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_animations_list: {
        parameters: {
            query?: {
                project?: string;
                /**
                 * @description * `QUEUED` - Queued
                 *     * `RENDERING` - Rendering
                 *     * `DONE` - Done
                 *     * `ERROR` - Error
                 *     * `CANCELED` - Canceled
                 */
                status?: "CANCELED" | "DONE" | "ERROR" | "QUEUED" | "RENDERING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Animation"][];
                };
            };
        };
    };
    api_animations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Animation"];
                "application/x-www-form-urlencoded": components["schemas"]["Animation"];
                "multipart/form-data": components["schemas"]["Animation"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Animation"];
                };
            };
        };
    };
    api_animations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this animation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Animation"];
                };
            };
        };
    };
    api_animations_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this animation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Animation"];
                "application/x-www-form-urlencoded": components["schemas"]["Animation"];
                "multipart/form-data": components["schemas"]["Animation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Animation"];
                };
            };
        };
    };
    api_animations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this animation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_animations_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this animation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAnimation"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAnimation"];
                "multipart/form-data": components["schemas"]["PatchedAnimation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Animation"];
                };
            };
        };
    };
    api_assets_list: {
        parameters: {
            query?: {
                project?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"][];
                };
            };
        };
    };
    api_assets_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Asset"];
                "*/*": components["schemas"]["Asset"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    api_assets_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this asset. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    api_assets_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this asset. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Asset"];
                "*/*": components["schemas"]["Asset"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    api_assets_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this asset. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_assets_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this asset. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedAsset"];
                "*/*": components["schemas"]["PatchedAsset"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    api_heartbeat_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_heartbeat_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_jobs_list: {
        parameters: {
            query?: {
                animation?: number;
                asset__project?: string;
                assigned_worker?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `QUEUED` - Queued
                 *     * `RENDERING` - Rendering
                 *     * `DONE` - Done
                 *     * `ERROR` - Error
                 *     * `CANCELED` - Canceled
                 */
                status?: "CANCELED" | "DONE" | "ERROR" | "QUEUED" | "RENDERING";
                tiled_job?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    api_jobs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Job"];
                "application/x-www-form-urlencoded": components["schemas"]["Job"];
                "multipart/form-data": components["schemas"]["Job"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    api_jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Render Job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    api_jobs_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Render Job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Job"];
                "application/x-www-form-urlencoded": components["schemas"]["Job"];
                "multipart/form-data": components["schemas"]["Job"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    api_jobs_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Render Job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_jobs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Render Job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedJob"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedJob"];
                "multipart/form-data": components["schemas"]["PatchedJob"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    api_jobs_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Render Job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Job"];
                "application/x-www-form-urlencoded": components["schemas"]["Job"];
                "multipart/form-data": components["schemas"]["Job"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    api_jobs_claim_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Render Job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Job"];
                "application/x-www-form-urlencoded": components["schemas"]["Job"];
                "multipart/form-data": components["schemas"]["Job"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    api_jobs_upload_output_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Render Job. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Job"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    api_projects_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    api_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProject"];
                "multipart/form-data": components["schemas"]["PatchedProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_projects_pause_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_projects_unpause_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this project. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    api_tiled_jobs_list: {
        parameters: {
            query?: {
                project?: string;
                /**
                 * @description * `QUEUED` - Queued
                 *     * `RENDERING` - Rendering
                 *     * `ASSEMBLING` - Assembling
                 *     * `DONE` - Done
                 *     * `ERROR` - Error
                 */
                status?: "ASSEMBLING" | "DONE" | "ERROR" | "QUEUED" | "RENDERING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TiledJob"][];
                };
            };
        };
    };
    api_tiled_jobs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TiledJob"];
                "application/x-www-form-urlencoded": components["schemas"]["TiledJob"];
                "multipart/form-data": components["schemas"]["TiledJob"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TiledJob"];
                };
            };
        };
    };
    api_tiled_jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tiled job. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TiledJob"];
                };
            };
        };
    };
    api_tiled_jobs_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tiled job. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TiledJob"];
                "application/x-www-form-urlencoded": components["schemas"]["TiledJob"];
                "multipart/form-data": components["schemas"]["TiledJob"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TiledJob"];
                };
            };
        };
    };
    api_tiled_jobs_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tiled job. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_tiled_jobs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tiled job. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTiledJob"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTiledJob"];
                "multipart/form-data": components["schemas"]["PatchedTiledJob"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TiledJob"];
                };
            };
        };
    };
}
