# SPDX-FileCopyrightText: 2025 Dryad and Naiad Software LLC
#
# SPDX-License-Identifier: GPL-2.0-or-later
"""
Integration tests for the Job lifecycle.

Covers: create, claim, double-claim conflict, output upload
with thumbnail generation, and cancel.
"""

import io

import pytest
from PIL import Image

from workers.models import Job, JobStatus

JOBS_URL = '/api/jobs/'


def _make_test_image():
    """Create a minimal valid PNG in-memory."""
    buf = io.BytesIO()
    img = Image.new('RGB', (64, 64), color='red')
    img.save(buf, format='PNG')
    buf.seek(0)
    buf.name = 'output.png'
    return buf


@pytest.mark.django_db
class TestJobCreate:

    def test_create_job_returns_201(self, admin_client, asset):
        """Creating a job returns 201 and links to asset."""
        resp = admin_client.post(
            JOBS_URL,
            data={
                'name': 'RenderJob001',
                'asset_id': asset.pk,
                'output_file_pattern': '//render/#.png',
            },
            format='json',
        )
        assert resp.status_code == 201
        assert resp.data['name'] == 'RenderJob001'
        assert resp.data['status'] == 'QUEUED'
        assert resp.data['asset']['id'] == asset.pk


@pytest.mark.django_db
class TestJobClaim:

    def test_worker_claims_job(
        self, admin_client, worker_with_token, asset,
    ):
        """Worker claims QUEUED job -- status becomes RENDERING."""
        worker, worker_client = worker_with_token

        create_resp = admin_client.post(
            JOBS_URL,
            data={
                'name': 'ClaimTestJob',
                'asset_id': asset.pk,
                'output_file_pattern': '//render/#.png',
            },
            format='json',
        )
        job_id = create_resp.data['id']

        resp = worker_client.post(
            f'{JOBS_URL}{job_id}/claim/',
            data={'worker_id': worker.pk},
            format='json',
        )
        assert resp.status_code == 200
        assert resp.data['status'] == 'RENDERING'

        job = Job.objects.get(pk=job_id)
        assert job.assigned_worker == worker
        assert job.started_at is not None

    def test_double_claim_returns_409(
        self, admin_client, worker_with_token, asset,
    ):
        """Claiming an already-claimed job returns 409."""
        worker, worker_client = worker_with_token

        create_resp = admin_client.post(
            JOBS_URL,
            data={
                'name': 'DoubleClaim1',
                'asset_id': asset.pk,
                'output_file_pattern': '//render/#.png',
            },
            format='json',
        )
        job_id = create_resp.data['id']

        # First claim succeeds
        worker_client.post(
            f'{JOBS_URL}{job_id}/claim/',
            data={'worker_id': worker.pk},
            format='json',
        )

        # Second claim fails
        resp = worker_client.post(
            f'{JOBS_URL}{job_id}/claim/',
            data={'worker_id': worker.pk},
            format='json',
        )
        assert resp.status_code == 409


@pytest.mark.django_db(transaction=True)
class TestJobOutputUpload:

    def test_upload_output_saves_file_and_generates_thumbnail(
        self, admin_client, worker_with_token, asset,
    ):
        """Uploading output file saves it and triggers thumbnail.

        Uses ``transaction=True`` because Issue #118 moved thumbnail
        generation to ``transaction.on_commit``; on_commit callbacks
        only fire when the outer transaction actually commits, which
        never happens under the default wrapped-in-transaction
        ``django_db`` fixture.
        """
        worker, worker_client = worker_with_token

        create_resp = admin_client.post(
            JOBS_URL,
            data={
                'name': 'UploadTest1',
                'asset_id': asset.pk,
                'output_file_pattern': '//render/#.png',
            },
            format='json',
        )
        job_id = create_resp.data['id']

        # Claim the job first
        worker_client.post(
            f'{JOBS_URL}{job_id}/claim/',
            data={'worker_id': worker.pk},
            format='json',
        )

        # Upload output
        img_file = _make_test_image()
        resp = worker_client.post(
            f'{JOBS_URL}{job_id}/upload_output/',
            data={'output_file': img_file},
            format='multipart',
        )
        assert resp.status_code == 200

        job = Job.objects.get(pk=job_id)
        assert job.output_file is not None
        assert job.output_file.name != ''
        # Thumbnail should have been generated by signal
        assert job.thumbnail is not None
        assert job.thumbnail.name != ''


@pytest.mark.django_db
class TestJobCancel:

    def test_cancel_queued_job(self, admin_client, asset):
        """Canceling a QUEUED job sets status to CANCELED."""
        create_resp = admin_client.post(
            JOBS_URL,
            data={
                'name': 'CancelTest1',
                'asset_id': asset.pk,
                'output_file_pattern': '//render/#.png',
            },
            format='json',
        )
        job_id = create_resp.data['id']

        resp = admin_client.post(f'{JOBS_URL}{job_id}/cancel/')
        assert resp.status_code == 200
        assert resp.data['status'] == 'CANCELED'

        job = Job.objects.get(pk=job_id)
        assert job.status == JobStatus.CANCELED
        assert job.completed_at is not None

    def test_cancel_done_job_returns_409(self, admin_client, asset):
        """Cannot cancel a DONE job."""
        create_resp = admin_client.post(
            JOBS_URL,
            data={
                'name': 'CancelDone1',
                'asset_id': asset.pk,
                'output_file_pattern': '//render/#.png',
            },
            format='json',
        )
        job_id = create_resp.data['id']

        # Force to DONE
        job = Job.objects.get(pk=job_id)
        job.status = JobStatus.DONE
        job.save()

        resp = admin_client.post(f'{JOBS_URL}{job_id}/cancel/')
        assert resp.status_code == 409
