# SPDX-FileCopyrightText: 2025 Dryad and Naiad Software LLC
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Generated by Django 5.2.4 on 2026-03-31 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_animation_name_alter_job_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='workers.asset'),
        ),
        migrations.AlterField(
            model_name='job',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workers.asset'),
        ),
        migrations.AlterField(
            model_name='tiledjob',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiled_jobs', to='workers.asset'),
        ),
    ]
