# Generated by Django 5.2.4 on 2026-03-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_asset_fk_protect_to_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RENDERING', 'Rendering'), ('DONE', 'Done'), ('ERROR', 'Error'), ('CANCELED', 'Canceled')], default='QUEUED', max_length=50),
        ),
    ]
