# Generated by Django 5.2.4 on 2026-04-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_animation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='ui_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
