# Generated by Django 5.2.4 on 2026-04-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_finalize_blender_version_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='cpu_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='gpu_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RENDERING', 'Rendering'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20),
        ),
    ]
