# Generated by Django 5.2.4 on 2026-04-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_worker_cpu_name_worker_gpu_name_worker_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_paused', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Queue Setting',
                'verbose_name_plural': 'Queue Settings',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='auto_requeue_count',
            field=models.IntegerField(default=0, help_text='Number of times this job has been auto-requeued by stuck job detection.'),
        ),
    ]
