# Generated by Django 5.2.4 on 2026-04-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_queuesetting_job_auto_requeue_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='A unique name for the asset file.', max_length=255, unique=True),
        ),
    ]
