# Generated by Django 5.2.4 on 2026-04-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_alter_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='If true, this job is skipped during worker polling.'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'is_paused'], name='workers_job_status_c3d401_idx'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_paused',
        ),
    ]
