# Generated by Django 5.2.4 on 2026-04-06 22:19

import workers.models.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_add_job_is_paused_and_remove_project_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='video_error',
            field=models.TextField(blank=True, default='', help_text='Error message from failed video assembly.'),
        ),
        migrations.AddField(
            model_name='animation',
            name='video_file',
            field=models.FileField(blank=True, help_text='The assembled video file.', max_length=512, null=True, upload_to=workers.models.upload_paths.animation_video_upload_path),
        ),
        migrations.AddField(
            model_name='animation',
            name='video_settings',
            field=models.JSONField(blank=True, default=None, help_text='Video assembly configuration: preset, container, codec, framerate, crf.', null=True),
        ),
        migrations.AddField(
            model_name='animation',
            name='video_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ASSEMBLING', 'Assembling'), ('DONE', 'Done'), ('ERROR', 'Error')], default=None, help_text='Current state of video assembly.', max_length=20, null=True),
        ),
    ]
