# Generated by Django 5.2.4 on 2026-04-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0014_animation_video_error_animation_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='frame_step',
            field=models.IntegerField(default=1, help_text='Number of frames to advance between renders.'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='render_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Blender render settings overrides.'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='total_render_time_seconds',
            field=models.IntegerField(default=0, help_text='Cumulative render time of all completed frames.'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='video_settings',
            field=models.JSONField(blank=True, default=None, help_text='Video assembly config: preset, container, codec, etc.', null=True),
        ),
    ]
