# Generated by Django 5.2.4 on 2026-04-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_alter_animation_frame_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='render_device',
            field=models.CharField(choices=[('CPU', 'CPU Only'), ('GPU', 'GPU Only'), ('ANY', 'Any Available Device')], db_index=True, default='ANY', max_length=10),
        ),
    ]
