# SPDX-FileCopyrightText: 2025 Dryad and Naiad Software LLC
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Generated by Django 5.2.4 on 2026-04-12 05:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0017_managersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='yield_requeue_count',
            field=models.IntegerField(default=0, help_text='Number of times this job has been yield-requeued (artist return). Separate from auto_requeue_count (stuck job detection).'),
        ),
        migrations.AddField(
            model_name='worker',
            name='schedule_config',
            field=models.JSONField(blank=True, default=dict, help_text="Informational: worker's local claim_window schedule, reported via heartbeat."),
        ),
        migrations.CreateModel(
            name='WorkerYieldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('artist_return_gpu_contention', 'Artist Return (GPU Contention)'), ('artist_return_app_launch', 'Artist Return (App Launch)'), ('artist_return_session_unlock', 'Artist Return (Session Unlock)'), ('artist_return_sustained_activity', 'Artist Return (Sustained Activity)'), ('manual_override', 'Manual Override'), ('schedule_window_closed', 'Schedule Window Closed')], max_length=50)),
                ('grace_outcome', models.CharField(choices=[('finished', 'Finished'), ('aborted', 'Aborted')], max_length=20)),
                ('progress_at_yield', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('job_name', models.CharField(blank=True, default='', help_text='Denormalized job name for display after job deletion.', max_length=40)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_events', to='workers.worker')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['worker', '-timestamp'], name='workers_wor_worker__5db5ca_idx')],
            },
        ),
    ]
