# SPDX-FileCopyrightText: 2025 Dryad and Naiad Software LLC
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0018_add_yield_events_schedule_and_yield_requeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='ui_cert_fingerprint',
            field=models.CharField(
                max_length=64,
                blank=True,
                default='',
                help_text=(
                    "Self-reported SHA-256 fingerprint of the worker's "
                    "UI TLS certificate. NOT verified by the manager "
                    "-- do not use for security-critical decisions."
                ),
            ),
        ),
    ]
