# Generated by Django 5.2.4 on 2025-07-31 21:12

import django.db.models.deletion
import django.utils.timezone
import uuid
import workers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('output_file_pattern', models.CharField(max_length=1024)),
                ('start_frame', models.IntegerField()),
                ('end_frame', models.IntegerField()),
                ('frame_step', models.IntegerField(default=1, help_text='Number of frames to advance animation between renders (e.g., a step of 2 renders every other frame).')),
                ('status', models.CharField(default='QUEUED', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blender_version', models.CharField(default='4.5', help_text="e.g., '4.5' or '4.1.1'", max_length=100)),
                ('render_engine', models.CharField(choices=[('CYCLES', 'Cycles'), ('BLENDER_EEVEE_NEXT', 'Eevee'), ('WORKBENCH', 'Workbench')], default='CYCLES', max_length=50)),
                ('render_device', models.CharField(choices=[('CPU', 'CPU Only'), ('GPU', 'GPU Only'), ('ANY', 'Any Available Device')], default='ANY', max_length=10)),
                ('cycles_feature_set', models.CharField(choices=[('SUPPORTED', 'Supported'), ('EXPERIMENTAL', 'Experimental')], default='SUPPORTED', max_length=50)),
                ('render_settings', models.JSONField(blank=True, default=dict, help_text="Blender render settings overrides, e.g., {'cycles.samples': 128, 'resolution_x': 1920}")),
                ('total_render_time_seconds', models.IntegerField(default=0, help_text='The cumulative render time of all completed frames in this animation.')),
                ('tiling_config', models.CharField(choices=[('NONE', 'None'), ('2x2', '2x2 (4 Tiles)'), ('3x3', '3x3 (9 Tiles)'), ('4x4', '4x4 (16 Tiles)'), ('5x5', '5x5 (25 Tiles)')], default='NONE', help_text='Grid size for tiled rendering of each frame.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the asset file.', max_length=255, unique=True)),
                ('blend_file', models.FileField(help_text='The uploaded .blend file.', upload_to=workers.models.asset_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paused', models.BooleanField(default=False, help_text='If true, workers will not pick up jobs from this project.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_tools', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='AnimationFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RENDERING', 'Rendering'), ('ASSEMBLING', 'Assembling'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=50)),
                ('output_file', models.FileField(blank=True, help_text='The final, assembled output image for this frame.', null=True, upload_to=workers.models.animation_frame_output_upload_path)),
                ('render_time_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='workers.animation')),
            ],
            options={
                'ordering': ['animation', 'frame_number'],
                'unique_together': {('animation', 'frame_number')},
            },
        ),
        migrations.AddField(
            model_name='animation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animations', to='workers.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='workers.project'),
        ),
        migrations.AddField(
            model_name='animation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='workers.project'),
        ),
        migrations.CreateModel(
            name='TiledJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('final_resolution_x', models.IntegerField()),
                ('final_resolution_y', models.IntegerField()),
                ('tile_count_x', models.IntegerField(default=4)),
                ('tile_count_y', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RENDERING', 'Rendering'), ('ASSEMBLING', 'Assembling'), ('DONE', 'Done'), ('ERROR', 'Error')], default='QUEUED', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blender_version', models.CharField(default='4.5', max_length=100)),
                ('render_engine', models.CharField(choices=[('CYCLES', 'Cycles'), ('BLENDER_EEVEE_NEXT', 'Eevee'), ('WORKBENCH', 'Workbench')], default='CYCLES', max_length=50)),
                ('render_device', models.CharField(choices=[('CPU', 'CPU Only'), ('GPU', 'GPU Only'), ('ANY', 'Any Available Device')], default='ANY', max_length=10)),
                ('cycles_feature_set', models.CharField(choices=[('SUPPORTED', 'Supported'), ('EXPERIMENTAL', 'Experimental')], default='SUPPORTED', max_length=50)),
                ('render_settings', models.JSONField(blank=True, default=dict, help_text='Global render settings for all tiles.')),
                ('total_render_time_seconds', models.IntegerField(default=0)),
                ('output_file', models.FileField(blank=True, help_text='The final, assembled output image.', null=True, upload_to=workers.models.tiled_job_output_upload_path)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiled_jobs', to='workers.asset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiled_jobs', to='workers.project')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the render job.', max_length=255, unique=True)),
                ('output_file_pattern', models.CharField(help_text='Output file path pattern (e.g., //render/#.png)', max_length=1024)),
                ('start_frame', models.IntegerField(default=1)),
                ('end_frame', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RENDERING', 'Rendering'), ('DONE', 'Done'), ('ERROR', 'Error'), ('CANCELED', 'Canceled')], default='QUEUED', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blender_version', models.CharField(default='4.5', help_text="e.g., '4.5' or '4.1.1'", max_length=100)),
                ('render_engine', models.CharField(choices=[('CYCLES', 'Cycles'), ('BLENDER_EEVEE_NEXT', 'Eevee'), ('WORKBENCH', 'Workbench')], default='CYCLES', max_length=50)),
                ('render_device', models.CharField(choices=[('CPU', 'CPU Only'), ('GPU', 'GPU Only'), ('ANY', 'Any Available Device')], default='ANY', max_length=10)),
                ('cycles_feature_set', models.CharField(choices=[('SUPPORTED', 'Supported'), ('EXPERIMENTAL', 'Experimental')], default='SUPPORTED', max_length=50)),
                ('render_settings', models.JSONField(blank=True, default=dict, help_text="Blender render settings overrides, e.g., {'cycles.samples': 128, 'resolution_x': 1920}")),
                ('last_output', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('render_time_seconds', models.IntegerField(blank=True, help_text='The total time in seconds this job took to render.', null=True)),
                ('output_file', models.FileField(blank=True, help_text='The final rendered output file uploaded by the worker.', null=True, upload_to=workers.models.job_output_upload_path)),
                ('animation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workers.animation')),
                ('animation_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tile_jobs', to='workers.animationframe')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='workers.asset')),
                ('tiled_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workers.tiledjob')),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Render Job',
                'verbose_name_plural': 'Render Jobs',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
