# Generated by Django 5.2.4 on 2025-07-22 21:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the render job.', max_length=255, unique=True)),
                ('blend_file_path', models.CharField(help_text='Absolute path to the Blender file.', max_length=1024)),
                ('output_file_pattern', models.CharField(help_text='Output file path pattern (e.g., //render/#.png)', max_length=1024)),
                ('start_frame', models.IntegerField(default=1)),
                ('end_frame', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RENDERING', 'Rendering'), ('DONE', 'Done'), ('ERROR', 'Error'), ('CANCELED', 'Canceled')], default='QUEUED', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blender_version', models.CharField(default='4.5', help_text="e.g., '4.5' or 'blender-4.5.0-windows-x64'", max_length=100)),
                ('render_engine', models.CharField(default='CYCLES', help_text="e.g., 'CYCLES' or 'BLENDER_EEVEE'", max_length=100)),
                ('last_output', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Render Job',
                'verbose_name_plural': 'Render Jobs',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
