# Generated by Django 5.2.4 on 2026-03-31 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(help_text='A unique name for the render job within its asset.', max_length=40, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='tiledjob',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddConstraint(
            model_name='animation',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_animation_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('asset', 'name'), name='unique_job_name_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='tiledjob',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_tiledjob_name_per_project'),
        ),
    ]
