# Generated by Django 5.2.4 on 2025-07-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='available_tools',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
