# Generated by Django 5.2.4 on 2025-07-25 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_available_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('blend_file_path', models.CharField(max_length=1024)),
                ('output_file_pattern', models.CharField(max_length=1024)),
                ('start_frame', models.IntegerField()),
                ('end_frame', models.IntegerField()),
                ('status', models.CharField(default='QUEUED', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blender_version', models.CharField(default='4.5', help_text="e.g., '4.5' or 'blender-4.5.0-windows-x64'", max_length=100)),
                ('render_engine', models.CharField(default='CYCLES', help_text="e.g., 'CYCLES' or 'BLENDER_EEVEE'", max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workers.animation'),
        ),
    ]
