# Generated by Django 5.2.4 on 2025-07-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_animation_job_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='render_device',
            field=models.CharField(default='CPU', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='render_device',
            field=models.CharField(default='CPU', max_length=10),
        ),
    ]
