# Generated by Django 5.2.4 on 2025-07-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_animation_render_device_job_render_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='total_render_time_seconds',
            field=models.IntegerField(default=0, help_text='The cumulative render time of all completed frames in this animation.'),
        ),
        migrations.AddField(
            model_name='job',
            name='render_time_seconds',
            field=models.IntegerField(blank=True, help_text='The total time in seconds this job took to render.', null=True),
        ),
    ]
